// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhtzkqrogfyvkkpjcrrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZodHprcXJvZ2Z5dmtrcGpjcnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Njk5NDQsImV4cCI6MjA3MTI0NTk0NH0.jiGoB_ym-NkEEomjj3svvkqkoQ9_KRzh05jzIh5snhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});